version: '3.8'

services:
  musicspace-service:
    image: takeone/musicspace-service:dev-latest-amd64
    restart: unless-stopped
    entrypoint: ["/src/bin/entrypoint.sh"]
    command: ["sh", "/src/bin/command.sh"]
    build:
      context: ./musicspace
    ports:
      - 3000:8000
    env_file:
      - dev.musicspace-service.env
      - dev.musicspace-service.override.env
    volumes:
      - ./musicspace:/src
      - ./data/musicspace-service/emails:/tmp/emails
      - ./data/musicspace-service:/var/musicspace
    depends_on:
      - musicspace-minio

  musicspace-minio:
    restart: unless-stopped
    image: takeone/musicspace-minio:dev-local-latest
    command: ["sh", "/src/bin/command.sh"]
    build:
      context: ./minio
    environment:
      API_PORT: 3001
      CONSOLE_PORT: 3002
      DATA_DIRECTORY: /var/minio/data
    volumes:
      - ./minio/scripts:/src/bin
      - ./data/minio:/var/minio/data
    ports:
      - 3001:3001
      - 3002:3002