# Generated by Django 4.1.4 on 2023-01-03 17:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('musicspace_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street_1', models.CharField(max_length=128)),
                ('street_2', models.CharField(blank=True, max_length=128)),
                ('city', models.CharField(max_length=128)),
                ('state', models.CharField(max_length=64)),
                ('zip', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('display_text', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('display_text', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, default='', max_length=256)),
                ('text', models.TextField(blank=True, default='')),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('nonbinary', 'Nonbinary'), ('other', 'Other')], max_length=16)),
                ('image_url', models.CharField(blank=True, default='', max_length=256)),
                ('in_person', models.BooleanField()),
                ('online', models.BooleanField()),
                ('genres', models.ManyToManyField(to='musicspace_app.genre')),
                ('instruments', models.ManyToManyField(to='musicspace_app.instrument')),
                ('location', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='provider', to='musicspace_app.address')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='provider_opt', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
