# Generated by Django 4.1.5 on 2023-02-08 02:26

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('musicspace_app', '0003_data_migration'),
    ]

    operations = [
        migrations.CreateModel(
            name='TakeOneUser',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('takeone_id', models.CharField(editable=False, max_length=64)),
                ('active', models.BooleanField(default=True)),
                ('created_date_time', models.DateTimeField(auto_now_add=True)),
                ('modified_date_time', models.DateTimeField(auto_now=True)),
                ('provider', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='takeone_user_opt', to='musicspace_app.provider')),
            ],
            options={
                'ordering': ['created_date_time'],
            },
        ),
        migrations.CreateModel(
            name='TakeOneProject',
            fields=[
                ('id', models.CharField(editable=False, max_length=64, primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=64)),
                ('published', models.BooleanField(default=False)),
                ('show_video', models.BooleanField(default=False)),
                ('created_date_time', models.DateTimeField(auto_now_add=True)),
                ('modified_date_time', models.DateTimeField(auto_now=True)),
                ('takeone_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='musicspace_app.takeoneuser')),
            ],
            options={
                'ordering': ['created_date_time'],
            },
        ),
    ]
