# Generated by Django 4.1.5 on 2023-06-13 12:46

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('musicspace_app', '0003_data_migration'),
    ]

    operations = [
        migrations.CreateModel(
            name='TakeOneUser',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('takeone_id', models.CharField(editable=False, max_length=64)),
                ('active', models.BooleanField(default=True)),
                ('created_date_time', models.DateTimeField(auto_now_add=True)),
                ('modified_date_time', models.DateTimeField(auto_now=True)),
                ('provider', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='takeone_user_opt', to='musicspace_app.provider')),
            ],
            options={
                'ordering': ['created_date_time'],
            },
        ),
        migrations.CreateModel(
            name='TakeOneProfileVideoContainer',
            fields=[
                ('id', models.CharField(editable=False, max_length=64, primary_key=True, serialize=False)),
                ('template', models.CharField(editable=False, max_length=64)),
                ('video_stream_src', models.CharField(blank=True, default='', max_length=512)),
                ('video_stream_type', models.CharField(blank=True, default='', max_length=512)),
                ('video_stream_video_format', models.CharField(blank=True, choices=[('landscape', 'Landscape'), ('portrait', 'Portrait'), ('square', 'Square')], max_length=16)),
                ('created_date_time', models.DateTimeField(auto_now_add=True)),
                ('modified_date_time', models.DateTimeField(auto_now=True)),
                ('takeone_user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='profile_video_container', to='musicspace_app.takeoneuser')),
            ],
        ),
    ]
